// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDqyZ9KOrq6Z01ew05Ys8-_DWNTn2WQtA',
    appId: '1:712683613023:web:733db48033c482ac2b24ea',
    messagingSenderId: '712683613023',
    projectId: 'al-qur--an',
    authDomain: 'al-qur--an.firebaseapp.com',
    storageBucket: 'al-qur--an.appspot.com',
    measurementId: 'G-MFBMY16DTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxUJzeB6a9NvzQFjonuy4KeEGuIGxjUUA',
    appId: '1:712683613023:android:321bc6d73ba23e382b24ea',
    messagingSenderId: '712683613023',
    projectId: 'al-qur--an',
    storageBucket: 'al-qur--an.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADCkTYPZ0u2SkYjeDpb1lv1zOX32i3QDg',
    appId: '1:712683613023:ios:1f413bf94e983fb32b24ea',
    messagingSenderId: '712683613023',
    projectId: 'al-qur--an',
    storageBucket: 'al-qur--an.appspot.com',
    androidClientId: '712683613023-o0nj6ivb3iuo024tsf8971epsahfdpm2.apps.googleusercontent.com',
    iosClientId: '712683613023-10clth1hqjd4ab8teidvc6dpuiidb5cr.apps.googleusercontent.com',
    iosBundleId: 'id.smilecodes.quran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADCkTYPZ0u2SkYjeDpb1lv1zOX32i3QDg',
    appId: '1:712683613023:ios:1f413bf94e983fb32b24ea',
    messagingSenderId: '712683613023',
    projectId: 'al-qur--an',
    storageBucket: 'al-qur--an.appspot.com',
    androidClientId: '712683613023-o0nj6ivb3iuo024tsf8971epsahfdpm2.apps.googleusercontent.com',
    iosClientId: '712683613023-10clth1hqjd4ab8teidvc6dpuiidb5cr.apps.googleusercontent.com',
    iosBundleId: 'id.smilecodes.quran',
  );
}
